language: python

python: 
  - "3.5"

services:
  - postgresql

before_install:
  - createdb mt2414
  - psql -d mt2414 -f mt2414/db.sql

install:
  - pip install pylint
  - pip install pyexcel-xlsx
  - pip install pyexcel-xls
  - pip install pyotp
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - echo "Tests are currently disabled. Enable them when you are ready to test."
  #- pylint mt2414/main.py
  #- run unit tests

after_script:
  - gunicorn mt2414.main:app &
  - curl -X POST -d "username=test" -d "password=password" "http://localhost:8000/v1/auth"
