language: python

python: 
  - "3.5"

services:
  - postgresql

before_install:
  - psql createdb mt2414
  - psql -d mt2414 -f mt2414/db.sql

install:
  - pip install pyexcel-xlsx
  - pip install pyexcel-xls
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - mt2414/main
