language: python

python: 
  - "3.5"

services:
  - postgresql

before_install:
  - createdb mt2414
  - psql -d mt2414 -f mt2414/db.sql

install:
  - pip install pylint
  - pip install pyexcel-xlsx
  - pip install pyexcel-xls
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - pylint mt2414/main.py
